[supervisord]
nodaemon=true
user=root  ;
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=50MB
logfile_backups=3

[program:module]
user=root
command=python -u test_anomalies.py
command=python -u main.py
autostart=true
autorestart=true
startsecs=5
stopwaitsecs=10
user=root
environment=PYTHONUNBUFFERED="1"
stdout_logfile=/var/log/app_out.log
stderr_logfile=/var/log/app_err.log
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB
redirect_stderr=true

[program:telegram_bot]
user=root
command=python bot.py
autostart=true
autorestart=true
startsecs=20
exitcodes=0
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/telegram_bot.log
logfile_maxbytes=150MB